### PR TITLE
Update demo.md

### PR DESCRIPTION
**Pull request by nielsdrost**
Replaced demo page with link to demo machine. Also needs a link to the form to signup.

### CODE REVIEW

**Comment by nielsdrost** [comment]
P.s. I also added the demo page to the menu.

**Review by RolfHut — APPROVED** [review]
Looks good

**Comment by RolfHut** [comment]
do I remove the branch, or does the one who initiated the pull request
delete it?

Rolf
-- 
PS my working hours may not be your working hours. Please only reply in
your working hours

*--*
*dr. ir. Rolf Hut*
MacGyver Associate Professor in Water Resources and Maker Education at Delft
University of Technology
<http://www.tudelft.nl/>
Public speaker on Technology and Innovation for Everyone
Columnist at De Ingenieur <https://www.deingenieur.nl/artikel/quarantandem>
Writer of Rolfs Maakbare Wereld
<http://rolfhut.nl/rolfsmaakbarewereldbolcom> and Knotsgekke Surprises voor
Iedereen <http://rolfhut.nl/surpriseboek>.
www.rolfhut.nl/english
@RolfHut ***@***.***>

*Recent papers*
Hut et al.: Easy to build low-power GPS drifters with local storage and a
cellular modem made from off-the-shelf components
<https://doi.org/10.5194/gi-9-435-2020>, Geoscientific Instrumentation,
Methods and Data Systems 2020
Hut et al.: Teaching a hands-on course during corona lockdown: from
problems to opportunities <https://doi.org/10.1088/1361-6552/abb06a>,
Physics Education 2020
Hut et al.: Taking a Breath of the Wild: are geoscientists more effective
than non-geoscientists in determining whether video game world landscapes
are realistic? <https://doi.org/10.5194/gc-2-117-2019>, Geoscience
Communication 2019

**Comment by Peter9192** [comment]
> do I remove the branch, or does the one who initiated the pull request delete it?

Now I did it. But you may as well remove it immediately after merging (there's even a setting to automate this, we could use it).

**Pull request merged**
